### ISSUE TITLE
Convert codebase to use redux.

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/Lingado#3]
The app currently only uses react-native. Using redux would make the codebase a lot cleaner.

**Comment by ManuelJF** [comment]
I will take this 👍
we only need to configure the store or refactor all container implementation of fecthing data to redux????

**Comment by maaslalani** [comment]
> I will take this 👍
> we only need to configure the store or refactor all container implementation of fecthing data to redux????

Right now I use device localStorage to persist information and access it across multiple screens. I would like to use a `Redux` store and then `PersistGate`

**Comment by agoiabel** [comment]
@ManuelJF @maaslalani, Can I also work on this?

**Comment by ManuelJF** [comment]
@maaslalani i wan't to working on this but i can't runing up the project with expo :(

**Comment by ManuelJF** [comment]
@agoiabel Yeah! Of course 👍

**Comment by maaslalani** [comment]
@ManuelJF What problems are you encountering?

**Comment by maaslalani** [comment]
@ManuelJF What versions of `npm` and `node` are you using?

**Comment by maaslalani** [comment]
@agoiabel Go ahead! :)

**Comment by maaslalani** [comment]
@ManuelJF I got it working, here are the steps I followed.

Clone the repo.
```
git clone https://github.com/maaslalani/Lingado/
```

Install `expo-cli`
```
npm install --global expo-cli
```

`cd` into the directory
```
cd Lingado
```

Install dependencies
```
npm install
```

Install expo on simulator
```
expo build:ios
```

Run expo `metro bundler`
```
expo start
```

Open the app on the simulator with the link given. It should look like this.
`exp://192.168.0.23:19000`
